name: slack - GitHub Actions Slack integration
description: Notify Slack of GitHub Actions workflows, jobs and step status.
author: satterly
inputs:
  status:
    description: Specify success, failure, cancelled or a custom status.
    required: true
  channel:
    description: Override default channel with different channel or username
    required: false
  downloadUrl:
    description: Artifact download URL
    required: false
  version:
    description: Artifact version
    required: true
  platform:
    description: Artifact platform
    required: true  
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: alert-circle
  color: red
